### ISSUE TITLE
Y axis rounds probablities to 0 or 1

### ISSUE THREAD

**Issue by kmichael08** [MI2DataLab/ceterisParibusExt#1]
For classification models, y axis displays probablities. However, all values are rounded to 0/1. In example below, it'd be good to have 0.5 displayed in the middle
![screenshot_2019-02-11 ceterisparibus d3 template](https://user-images.githubusercontent.com/15304831/52567259-282c7c00-2e0c-11e9-9f10-4efd13643cb4.png)

Here is the html with jsons:

[classification_example.tar.gz](https://github.com/MI2DataLab/ceterisParibusExt/files/2851278/classification_example.tar.gz)

**Comment by flaminka** [comment]
Sure, probably I added somewhere rounding :), will check and let you know when it's fixed.

**Comment by flaminka** [comment]
Issue solved :)

(new js code): https://github.com/MI2DataLab/ceterisParibusExt/blob/master/ceterisParibusD3/ceterisParibusD3.js

(commit):
https://github.com/MI2DataLab/ceterisParibusExt/commit/68fa2206cc15ef81b4b5899b9393564fe22ff93c
