### ISSUE TITLE
Color by variable values

### ISSUE THREAD

**Issue by kmichael08** [MI2DataLab/ceterisParibusExt#2]
Something strange happens when try to color by values of variable `children` as in example below:
![screenshot_2019-02-11 ceterisparibus d3 template 1](https://user-images.githubusercontent.com/15304831/52567908-b05f5100-2e0d-11e9-835f-34beee3c422d.png)

Files attached below:
[color_by_var_files.tar.gz](https://github.com/MI2DataLab/ceterisParibusExt/files/2851319/color_by_var_files.tar.gz)

**Comment by flaminka** [comment]
I will check and let you know when it's fixed :)

**Comment by flaminka** [comment]
Issue solved :)

(new js code): https://github.com/MI2DataLab/ceterisParibusExt/blob/master/ceterisParibusD3/ceterisParibusD3.js

(commit):
https://github.com/MI2DataLab/ceterisParibusExt/commit/68fa2206cc15ef81b4b5899b9393564fe22ff93c

**Comment by kmichael08** [comment]
Great, though I believe there is still some error in this function.
![screenshot_2019-02-14 ceterisparibuscheatsheet 1](https://user-images.githubusercontent.com/15304831/52780297-23eda200-304a-11e9-8cd7-1d379bf002ee.png)
Values on the legend are strange, and there are more than two colors on the plot

**Comment by flaminka** [comment]
(new js code): https://github.com/MI2DataLab/ceterisParibusExt/blob/master/ceterisParibusD3/ceterisParibusD3.js

(commit):
[68fa220](https://github.com/MI2DataLab/ceterisParibusExt/commit/cafc602b51d5855a2f27c17c2c5468c4b0a27922)
